=== Grupo6Edix/Tarea-AE-2-Lenguaje-Marcas/biblioteca_Jorge.dtd
<!ELEMENT biblioteca (nombre,direccion,prestamos)>
<!-- Elementos de biblioteca -->
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!-- Elemento de biblioteca con sus elementos hijos -->
<!ELEMENT prestamos (libro*,revista*,periodico*)>

<!-- Elementos de libro -->
<!ELEMENT libro (titulo,sinopsis,indice,capitulos)>
<!-- Atributo con identificador unico -->
<!ATTLIST libro id ID #REQUIRED>
<!-- Atributo con lista de seleccion -->
<!ATTLIST libro tipo_clase (novela | infantil | didactico) #REQUIRED>
<!ATTLIST libro paginas CDATA #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT sinopsis (#PCDATA)>
<!ELEMENT indice (#PCDATA)>
<!ELEMENT capitulos (capitulo+)>
    <!ELEMENT capitulo (contenido)>
    <!ATTLIST capitulo paginas CDATA #REQUIRED>
        <!-- Se decide que "contenido" sea vacio ya que lleva el enlace a consultar como atributo -->
        <!ELEMENT contenido EMPTY>
        <!ATTLIST contenido informacion CDATA #REQUIRED>

<!-- Elementos de revista -->
<!ELEMENT revista (titulo,numero,indice,secciones_revista)>
<!-- Atributo con identificador unico -->
<!ATTLIST revista id ID #REQUIRED>
<!-- Atributo con lista de seleccion -->
<!ATTLIST revista tipo_clase (informatica | corazon | coches | investigacion | otras) #REQUIRED>
<!ATTLIST revista paginas CDATA #REQUIRED>
<!-- No definimos el elemento "titulo" ni "indice" ya que lo hemos hecho con anterioridad -->
<!ELEMENT numero (#PCDATA)>
<!ELEMENT secciones_revista (seccion_revista+)>
    <!-- No definimos el elemento "contenido" ya que lo hemos hecho con anterioridad -->    
    <!ELEMENT seccion_revista (contenido)>
    <!ATTLIST seccion_revista paginas CDATA #REQUIRED>

<!-- Elementos de periodico -->
<!ELEMENT periodico (indice,secciones_periodico)>
<!-- Atributo con identificador unico -->
<!ATTLIST periodico id ID #REQUIRED>
<!-- Atributo con lista de seleccion -->
<!ATTLIST periodico tipo_clase (nacional | internacional) #REQUIRED>
<!ATTLIST periodico fecha_publicacion CDATA #REQUIRED>
<!-- No definimos el elemento "indice" ya que lo hemos hecho con anterioridad -->
<!ELEMENT secciones_periodico (seccion_periodico+)>
    <!ELEMENT seccion_periodico (articulo+)>
    <!-- Atributo con lista de seleccion -->
    <!ATTLIST seccion_periodico tipo (economia | opinion | deportes | nacional | internacional) #REQUIRED>
        <!ELEMENT articulo (autor,contenido)>
            <!ELEMENT autor (#PCDATA)>
            <!-- No definimos el elemento "contenido" ya que lo hemos hecho con anterioridad  -->

=== Grupo6Edix/Tarea-AE-2-Lenguaje-Marcas/biblioteca_conDTD_Jorge.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "biblioteca_Jorge.dtd">
<biblioteca>
   <nombre>Biblioteca Edix</nombre> 
   <direccion>Calle Aravaca, 12</direccion>
   <prestamos>
        <!-- XML sobre libro -->
        <libro id="L0001" tipo_clase="novela" paginas="800">
            <titulo>Don Quijote</titulo>
            <sinopsis>Narra las aventuras de Alonso Quijanoero</sinopsis>  
            <indice>Indice</indice>          
            <capitulos>
                <capitulo paginas="500">
                    <contenido informacion="https://es.wikipedia.org/wiki/Don_Quijote_de_la_Mancha"/>
                </capitulo>
                <capitulo paginas="300">
                    <contenido informacion="https://es.wikipedia.org/wiki/Don_Quijote_de_la_Mancha"/>
                </capitulo>
            </capitulos>           
        </libro>
        <libro id="L0002" tipo_clase="infantil" paginas="500">
            <titulo>Blancanieves</titulo>
            <sinopsis>Narra las aventuras de Blancanieves</sinopsis>  
            <indice>Indice</indice>          
            <capitulos>
                <capitulo paginas="500">
                    <contenido informacion="https://es.wikipedia.org/wiki/Blancanieves"/>
                </capitulo>
            </capitulos>           
        </libro>
        <!-- XML sobre revista -->
        <revista id="R0001" tipo_clase="informatica" paginas="1">
            <titulo>HobbyConsolas</titulo>
            <numero>157</numero>
            <indice>Indice</indice>
            <secciones_revista>
                <seccion_revista paginas="5">
                    <contenido informacion="https://www.hobbyconsolas.com/noticias/team-cherry-deseando-mostrar-novedades-hollow-knight-silksong-no-haran-esperar-mucho-1059445"/>
                </seccion_revista>
                <seccion_revista paginas="10">
                    <contenido informacion="https://www.hobbyconsolas.com/noticias/batman-unreal-engine-5-podria-verse-juego-batman-next-gen-1059457"/>
                </seccion_revista>
            </secciones_revista>
        </revista>
        <revista id="R0002" tipo_clase="informatica" paginas="1">
            <titulo>Meristation</titulo>
            <numero>50</numero>
            <indice>Indice</indice>
            <secciones_revista>
                <seccion_revista paginas="20">
                    <contenido informacion="https://as.com/meristation/2022/05/16/noticias/1652688992_752989.html"/>
                </seccion_revista>
            </secciones_revista>
        </revista>
        <!-- XML sobre periodico -->
        <periodico id="P0001" tipo_clase="nacional" fecha_publicacion="11/05/2022">
            <indice>Indice</indice>
            <secciones_periodico>
                <seccion_periodico tipo="deportes">
                    <articulo>
                        <autor>Jordi Quixano</autor>
                        <contenido informacion="https://elpais.com/deportes/2022-05-11/el-barcelona-de-balonmano-se-arrima-a-la-final-four-de-la-champions.html"/>
                    </articulo>
                </seccion_periodico>
            </secciones_periodico>
        </periodico>
        <periodico id="P0002" tipo_clase="internacional" fecha_publicacion="16/05/2022">
            <indice>Indice</indice>
            <secciones_periodico>
                <seccion_periodico tipo="internacional">
                    <articulo>
                        <autor>Marcel Krueger</autor>
                        <contenido informacion="https://edition.cnn.com/travel/article/wuppertal-schwebebahn-suspension-railway-germany/index.html"/>
                    </articulo>
                    <articulo>
                        <autor>Oliver Berg</autor>
                        <contenido informacion="https://edition.cnn.com/travel/article/wuppertal-schwebebahn-suspension-railway-germany/index.html"/>
                    </articulo>
                </seccion_periodico>
            </secciones_periodico>
        </periodico>
   </prestamos>
</biblioteca>
